"""add patient_hospital_mappings and patient_doctor_assignments tables

Revision ID: 62dfef6d0f9b
Revises: cf83fff3a435
Create Date: 2026-08-11 22:55:08.002560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dfef6d0f9b'
down_revision = 'cf83fff3a435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_doctor_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_doctor_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_doctor_id'], ['hospital_doctors.hospital_doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('patient_hospital_mappings',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('access_code', sa.String(length=13), nullable=False),
    sa.Column('code_status', sa.Enum('active', 'used', 'expired', name='code_status_enum'), nullable=False),
    sa.Column('code_generated_at', sa.DateTime(), nullable=False),
    sa.Column('code_expires_at', sa.DateTime(), nullable=False),
    sa.Column('code_used_at', sa.DateTime(), nullable=True),
    sa.Column('share_pre_connection_history', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_doctor_id'], ['hospital_doctors.hospital_doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('access_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_hospital_mappings')
    op.drop_table('patient_doctor_assignments')
    # ### end Alembic commands ###
