"""add state to hospitals

Revision ID: 67303760e0dc
Revises: 7ded34235124
Create Date: 2026-08-11 13:08:42.167495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67303760e0dc'
down_revision = '7ded34235124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
