"""add profile fields to doctors

Revision ID: 7ded34235124
Revises: b0aa1cba77f1
Create Date: 2026-08-09 17:33:10.713342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ded34235124'
down_revision = 'b0aa1cba77f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hospitals_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hospital_timings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('hospital_timings')
        batch_op.drop_column('hospitals_text')
        batch_op.drop_column('specialization')
        batch_op.drop_column('qualification')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
