"""add hospital_doctors table

Revision ID: cf83fff3a435
Revises: 67303760e0dc
Create Date: 2026-08-11 22:31:15.829114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf83fff3a435'
down_revision = '67303760e0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_doctors',
    sa.Column('hospital_doctor_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('timings', sa.String(length=255), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.Enum('visiting', 'permanent', name='employment_type_enum'), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('hospital_doctor_id'),
    sa.UniqueConstraint('hospital_id', 'login_email', name='uq_hospital_doctor_login_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_doctors')
    # ### end Alembic commands ###
