"""Add patient_email to patient_hospital_mappings

Revision ID: d6fc941055cd
Revises: 62dfef6d0f9b
Create Date: 2026-08-12 20:47:43.203347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fc941055cd'
down_revision = '62dfef6d0f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_hospital_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_email', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_hospital_mappings', schema=None) as batch_op:
        batch_op.drop_column('patient_email')

    # ### end Alembic commands ###
