"""add vitals hot buffer warm trend cold ledger alerts log tables

Revision ID: fdeaa8ea88db
Revises: d6fc941055cd
Create Date: 2026-09-07 20:27:36.510273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeaa8ea88db'
down_revision = 'd6fc941055cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts_log',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('vitals_cold_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals_hot_buffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'CRITICAL', name='vitals_priority_enum'), nullable=False),
    sa.Column('source', sa.Enum('device', 'self', name='vitals_source_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vitals_hot_buffer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitals_hot_buffer_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('vitals_warm_trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitals_warm_trend')
    with op.batch_alter_table('vitals_hot_buffer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_hot_buffer_recorded_at'))

    op.drop_table('vitals_hot_buffer')
    op.drop_table('vitals_cold_ledger')
    op.drop_table('alerts_log')
    # ### end Alembic commands ###
